# Generated by Django 3.0.3 on 2020-02-27 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 27, 18, 2, 24, 232889, tzinfo=utc)),
        ),
    ]
