# Generated by Django 3.0.3 on 2020-02-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200227_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='postID',
            new_name='postid',
        ),
    ]
