# Generated by Django 3.0.3 on 2020-02-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200227_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='postid',
            new_name='postID',
        ),
    ]
